$mangasource='{
"sources":["mangapanda","mangareader","mangafox","bato","mangajoy","mangasee"],
"source-details": {
					 "mangapanda":{
							"url":"http://mangapanda.com/",
							"series-url":"http://mangapanda.com/<series_name>/",
							"chapter-url":"http://mangapanda.com/<series_name>/<chapter_no>",
							"page-url":"http://mangapanda.com/<series_name>/<chapter_no>/<page_no>",
							"multiword-seperator":"-",
							"search-url":"http://www.mangareader.net/actions/search/?q=<search_query>",
              "image-matching-regex-string":"width=.*src=\"http.*jpg\"",
              "image-pattern":"jpg"
						},
						"mangareader":{
							"url":"http://mangareader.net/",
							"series-url":"http://mangareader.net/<series_name>/",
							"chapter-url":"http://mangareader.net/<series_name>/<chapter_no>",
							"page-url":"http://mangareader.net/<series_name>/<chapter_no>/<page_no>",
							"multiword-seperator":"-",
							"search-url":"http://www.mangapanda.com/actions/search/?q=<search_query>",
              "image-matching-regex-string":"width=.*src=\"http.*jpg\"",
              "image-pattern":"jpg"
						},
					 "mangafox":{
							"url":"http://mangafox.me/directory/",
							"series-url":"http://mangafox.me/manga/<series_name>/",
							"chapter-url":"http://mangafox.me/manga/<series_name>/<volume>/c<chapter_no>",
							"page-url":"http://mangafox.me/manga/<series_name>/<volume>/c<chapter_no>/<page_no>.html",
							"multiword-seperator":"_",
							"search-url":"http://mangafox.me/ajax/search.php?term=<search_query>",
							"volume-determine-url":"http://mangafox.me/manga/<series_name>/",
              "image-matching-regex-string":"src=\"http.*jpg\"",
              "image-pattern":"jpg"
					 },
					 "bato":{
							"url":"http://bato.to/",
							"series-url":"http://bato.to/comic/_/comics/<series_name>-comics-<random_no>",
							"chapter-url":"http://bato.to/read/_/<random_no>/<series_name>_<volume>_ch<chapter_no>/",
							"page-url":"http://bato.to/read/_/<random_no>/<series_name>_<volume>_ch<chapter_no>/<page_no>",
							"multiword-seperator":"-",
							"search-url":"http://bato.to/search?name_cond=c&name=<search_query>",
							"volume-determine-url":"http://mangafox.me/manga/<series_name>/",
              "image-matching-regex-string":"width=.*src=\"http.*jpg\"",
              "image-pattern":"jpg"
					 },
           "mangajoy":{
							"url":"http://manga-joy.com/",
							"series-url":"http://manga-joy.com/<series_name>/",
							"chapter-url":"http://manga-joy.com/<series_name>/<chapter_no>",
							"page-url":"http://manga-joy.com/<series_name>/<chapter_no>/<page_no>",
							"multiword-seperator":"-",
              "image-matching-regex-string":"width=.*src=\"http.*[png|jpg]\"",
              "image-pattern":"jpg,png"
					 },
           "mangasee":{
							"url":"http://mangasee.co/",
							"series-url":"http://mangasee.co/manga/?series=<series_name>/",
							"chapter-url":"http://mangasee.co/manga/?series=<series_name>&chapter=<chapter_no>&index=1&page=1",
							"page-url":"http://mangasee.co/manga/?series=<series_name>&chapter=<chapter_no>&index=1&page=<page_no>",
							"multiword-seperator":"",
              "image-matching-regex-string":"src=\"http.*[png|jpg|]\"",
              "image-pattern":"jpg,png",
              "capitalize-series-name":"true"
					 }
			}
}'